[package]
name = "transactions_engine"
version = "1.0.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.3"
rust_decimal = { version = "1.36", features = ["serde-with-str"] }

[[bin]]
name = "transactions_engine"
path = "src/main.rs"
